name: example-instance

labels:
  ethpandaops: rocks

ethereum:
  beacon_node_address: http://localhost:5052
  
outputs:
- name: basic
  type: http
  config:
    type: http
    address: http://localhost:8080
    # Better to use a NTP server close eg.
    #   time.aws.com - AWS
    #   time.windows.com - Azure
    #   time.google.com - GCP
    ntp_server: pool.ntp.org
    headers:
      Authorization: Someb64Value
    batch_size: 300
    batch_interval_seconds: 3
    max_items: 100000
